# Generated by Django 5.2.7 on 2025-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='card_back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_face',
            field=models.ImageField(blank=True, null=True, upload_to='card_face/'),
        ),
    ]
