# Generated by Django 5.2.7 on 2025-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_id_card_back_user_id_card_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_of_expertise',
            field=models.CharField(default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
