# Generated by Django 5.2.7 on 2025-12-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='creater',
            new_name='creator',
        ),
    ]
